### ISSUE TITLE
Wrong name of ds

### ISSUE THREAD

**Issue by tuxpeople** [clastix/kubelived#14]
Hi

I just deployed this chart and after deployment, I got this:

```
[...]
   # Check the installer logs
   $ kubectl logs -f ds/kubelived-installer -n kube-system
[...]
```

Which is, I assume, this:
https://github.com/clastix/kubelived/blob/d721f89b6f4ce597df2a8ce03f715ea514521cc1/charts/kubelived/templates/NOTES.txt#L4

However, this does not work:
```
$ kubectl logs -f ds/kubelived-installer -n kube-system
Error from server (NotFound): daemonsets.apps "kubelived-installer" not found
```

In my case, this ds has another name:

```
$ kubectl get ds -n kube-system
NAME                   DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
keepalived-installer   1         1         1       1            1           <none>          3m15s
```

I read trough the `_helpers.tpl` but I'm not sure if the `NOTES.txt` is wrong or my deployment. My answers file basically only contains my VIP:

```yaml
keepalived:
  virtual_address: '192.168.8.8'
```

I used current master of this Git-Repo for deployment.

**Comment by bsctl** [comment]
@tuxpeople thanks for reporting this.
