### ISSUE TITLE
Supported Project?

### ISSUE THREAD

**Issue by snowy-jaguar** [clastix/kubelived#25]
Hi I'm sorry if this is the wrong type of channel to ask this but I'm wondering if this project is still supported because it's not seen a commit for 12 months and the pod security error issue was posted 9 months ago and I've just run into it

**Comment by thomasstxyz** [comment]
@SnowyJaguar1034  does not look like it's active :) , have a looks at https://github.com/kube-vip/kube-vip instead

**Comment by bsctl** [comment]
Project is no more supported.
